### ISSUE TITLE
The indicator keeps Pidgin running if I close Pidgin's buddy list or use the launcher's "quit"

### ISSUE THREAD

**Issue by muzso** [philipl/pidgin-indicator#23]
Actually there're multiple, but strongly related issues here:

1. The indicator plugin makes the buddy list into "just another" window of the application. I mean the indicator has a menu item called "Show Buddy List" which lets you show or hide the buddy list without exiting the application. Without this plugin if one closes the buddy list, Pidgin exits. I think this is an intended feature, but ...

2. If I close the buddy list window by clicking the usual "x" icon in the window's corner, the buddy list is hidden, but Unity's launcher switches the Pidgin icon into the "off" state as if Pidgin was not running.

3. If I richt-click Pidgin's icon in the launcher and select "Quit", again only the buddy list is hidden, but Pidgin keeps running.

Currently with the indicator plugin enabled you can only quit Pidgin by explicitly invoking it's "Quit" action, either by a keyboard shortcut (Ctrl+Q) or by going into it's menu and invoking "Buddies / Quit".

From the above list issue #1 might be considered a non-issue (i.e. a feature, although I'd like if it was configurable). But issue #2 and #3 are definitely bugs. At least from the POV of the standard Unity UI workflow.

P.S.: I'm using Ubuntu 14.04 (fully updated from the official repository).

**Comment by philipl** [comment]
This is just a function of how Pidigin and Unity work together, or don't.

1) Yes, this is a feature. The indicator's goal is to reimplement the same functionality that the old tray icon provided - and one of those features was that you could close all your windows and the app keeps running.

2) Unity only shows an active icon if a window is present. This is true for all apps. It's not smart but it's simple, so I assume that's why they did it that way.

3) Same thing - "Quit" makes it close the visible windows - it doesn't try and send the application a quit signal.

This behaviour is the same for pretty much any application that uses an indicator as a way to keep the app running when there are no windows open - unity doesn't handle them well.

**Comment by muzso** [comment]
Thank you for the quick response. :-) I had no idea about Unity's concept of an app "running". It's pretty strange though. One might even call it a design flaw (not to consider apps without windows as running).

Is there any chance that you might add an option (in the foreseeable future ;-) ) to the indicator plugin to let users disable the windowless behaviour (i.e. to rather exit upon the closure of the last open window, than keep running)?

My problem is that the Pidgin-supported indicator (i.e. the envelope icon of indicator-messages which gets it's input from Pidgin's libnotify plugin) sux big time. It doesn't give any visual feedback on the source of the "new message". The envelope simply turns blue for new emails and new Pidgin messages alike. I hate it.

It'd be nice to have best of both worlds: your indicator (with a separate icon for IM messages) and a well working integration with Unity (meaning that Pidgin exits when it's last window closes).

**Comment by philipl** [comment]
Someone could write a patch. I don't have the time to do so, but I'll happily accept a patch. The main issue is that it would require adding a preferences dialog, which is a bunch of tedious work.

Alternately, you can just delete the calls to **pidgin_blist_visibility_manager_add** and **pidgin_blist_visibility_manager_remove** and compile your own.
